### ISSUE TITLE
error when playing a song

### ISSUE THREAD

**Issue by fossfreedom** [asermax/lastfm_queue#3]
I occasionally see the following error when double clickng a song from my music library.

Traceback (most recent call last):
  File "/usr/lib/rhythmbox/plugins/rb/Loader.py", line 47, in _contents_cb
    (ok, contents, etag) = file.load_contents_finish(result)
  File "/usr/lib/python2.7/dist-packages/gi/types.py", line 43, in function
    return info.invoke(_args, *_kwargs)
gi._glib.GError: Automount failed: DBus error org.freedesktop.DBus.Error.InvalidArgs: Mountpoint Already registered

Its not consistent - not absolutely repeatable - but I've seen this several times today to make me report this.

**Comment by asermax** [comment]
I don't think that exception can't really be pinpointed on this plugin. It could be any other plugin that uses rb.Loader for http requests (althought you are probably testing it independently). And it's probably a misbehavior on rb itself.

Anyway, we can try to see if there's something in the plugin triggering that exception.
Other than the exception message, is there another noticeable change on the plugins behavior? e.g. the plugin doesn't add new tracks to the playing queue for that particular song.
If there's is, please post here the track info (title, artist, album) and anything you may find relevant to the context so I can compare against the code and do some test of my own.
If it's completely random and has no relation with the current track, then we probably should let it be xD

**Comment by fossfreedom** [comment]
No other plugins enabled.

Its not a particular track - it seems to be if I double click a track - wait 5 secs and double click another.  Repeat etc - it can usually be repeatable for this method.

It doesnt appear to cause the plugin to malfunction - it continues to retrieve info from lastfm.

Looking at https://live.gnome.org/RhythmboxPlugins/WritingGuide

there is a bit in the async io section that mentions this - the wording is

"Now that I've convinced you to use asynchronous IO, the question is how to do it. If you're doing more than just fetching URLs into memory, use GIO. If all you want to do is retrieve a small amount of data from a remote location, the rb.Loader class may be suitable"

emphasis on "small amount of data"

Speculation - maybe the quantity of data being returned is more than rb.Loader class was expecting and its throwing this error?

Anyway - its a small issue -  just wanted to let you know I have seen this error in the output.

**Comment by asermax** [comment]
Yep, it may have something to do with the amout of data being retrieved. I could try using the same threading model I've been using on my other plugins, but since this it's working like it's now... I really don't feel like changing it up.
I will mark it as wontfix for now, if something comes to my attention that makes me think I can fix it, or this bug turns to be something grave, I'll reopen this issue and work it out.

Anyway, thanks for the report :3

Edit: oh, it can also have to do with the current request being invalidated or lost given that you start another right away (by clicking another track in a short period of time). Nevertheless, I've no idea of how to 'correctly' cancel a request made through the Loader to make another one, so it's not like I can fix it :/ will have this issue into account anyway.
